### ISSUE TITLE
Module does not build with nginx v1.4.2

### ISSUE THREAD

**Issue by user00265** [rsms/afcgi#1]
I just tried building this on nginx v1.4.2 and, well, it seems that this has not been updated since the 0.8.x era. The error is included below.

```
cc -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
        -o objs/src/http/modules/ngx_http_fastcgi_module.o \
        src/http/modules/ngx_http_fastcgi_module.c
src/http/modules/ngx_http_fastcgi_module.c:264:7: error: ‘ngx_http_upsteam_bind_set_slot’ undeclared here (not in a function)
       ngx_http_upsteam_bind_set_slot,
       ^
make[1]: *** [objs/src/http/modules/ngx_http_fastcgi_module.o] Error 1
make[1]: Leaving directory `/home/eresto/nginx/src/nginx-1.4.2'
make: *** [build] Error 2
```

**Comment by rsms** [comment]
Trivia: This was [an actual typo](http://mdounin.ru/hg/nginx-mail/raw-rev/2da4537168f8) in nginx.
